### ISSUE TITLE
`generate_output_path` fails with "writing to read-only" when passed empty `output_path`

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaUtilities.jl#56]
Failure example [here](https://github.com/CliMA/ClimaAtmos.jl/actions/runs/9020764355/job/24786627579?pr=2994#step:6:1489).

**Comment by Sbozzolo** [comment]
Can you please provide a reproducer?

**Comment by Sbozzolo** [comment]
The particular build fails because `output_path_generator` is passed an empty `output_path` (because `job_id` for the configs in `tests` is empty). Passing an empty `output_path` is a user error, so I am fixing this by erroring out when the user passes an empty `output_path`.  That said, this was not an edge cases I considered and `output_path_generator` added a slash. As a result, `output_path_generator` tried writing to `"" + "/"`, which is read-only. 

I am changing this issue to target the particular build reported in the first message. Feel free to open a new one if you find another instance where the module fails.

**Comment by Sbozzolo** [comment]
We could treat `"" = "."`, but I personally think that it is never the case that the intent of the user is to pass an empty string as `output_path` and if the user wanted to write output to `.` they would have said so. When given `""`, it is impossible to sanitize the input and recover the user' intent. Instead, we should stop and inform the user that their input is invalid and they did something wrong. When a user passes an empty `output_path`, there probably something else that they are not doing correctly, and I would say that in this it is prefereable to produce a clear error message instead of choosing an arbitrary output folder.

**Comment by akshaysridhar** [comment]
Can we now remove the comment around 
https://github.com/CliMA/ClimaAtmos.jl/blob/0ee96c094a43c2f989a5925f106780d98edbc6a6/src/solver/type_getters.jl#L490-L494 ? cc @Sbozzolo

**Comment by Sbozzolo** [comment]
> Can we now remove the comment around https://github.com/CliMA/ClimaAtmos.jl/blob/0ee96c094a43c2f989a5925f106780d98edbc6a6/src/solver/type_getters.jl#L490-L494 ? cc @Sbozzolo

The speciifc problem reported was result of passing an empty `base_output_path`. This problem is still there (because `job_id` for the test cases is empty).
